= Agreement Between Trustees of the Forbes Library and Forbes Library Employee Association (FLEA): JULY 1, 2019 to JUNE 30, 2020 =
:toc:
:toc-placement: preamble
:sectnums!:
// Need some preamble to get TOC:
{empty}

== Article I: RECOGNITION ==

The Board recognizes the Forbes Library Employee Association (“FLEA”), for
purposes of collective bargaining, as the sole and exclusive representative of a
unit consisting of the following employees: All regular, full time and all
regular, non-temporary part time employees working more than twenty (20) hours
per week. The Board recognizes FLEA as the sole and exclusive bargaining agent
for the purpose of negotiating wages, hours and other terms and conditions of
employment for the employees covered by this contract.

== Article II: BOARD RIGHTS ==

It is agreed that except as specifically and directly modified by the express
language in a specific provision of this contract, the Board of Trustees of
Forbes Library retains all rights, obligations and powers that it has, or may in
the future be granted, by law, and may exercise such powers at its discretion.
It is understood that the Board has the right to initiate new policies and
procedures which do not affect, or conflict with, the terms and conditions of
this contract.

== Article III: ASSOCIATION RIGHTS ==

The Association shall have the privilege to use the Library facilities as are
normally used by the public; provided that such use does not interfere with
normal operation. Any additional cost arising from or related to such use shall
be borne by the Association. The Association shall have the right to use the
employees’ lounge.

The Board agrees to have the central financial office, with appropriate employee
authorization, deduct from employee salary Association dues, when, and if, FLEA
votes to require members to pay an agency fee (dues).

All employees covered by the recognition clause of this Agreement shall, after
completing thirty (30) days of employment, either authorize the employer to
deduct FLEA dues or shall authorize the deduction of an agency fee equal to the
amount of dues payable by Association members (less any amount assessed for
political/lobbying purposes).

Each employee waives all rights and claims to the monies so deducted and
relieves the Board, all of its officers, and any other agent acting on behalf of
said Board, from any and all liability related to this Article. The Association
agrees to indemnify the Board for any and all legal costs involved in defending
against a claim based on this dues deduction provision. Employees may initiate
or withdraw their authorization at any time, although it is understood that a
reasonable period of time, at least sixty days, will be required for such a
change to become effective.

The Association agrees that when it uses Library equipment (copier, etc.) for
Association purposes it shall immediately pay for such use in the same manner as
the general public. Abuse of this privilege will result in its withdrawal.

In addition, the Association members agree not to conduct union business during
work time. Association members who want to participate in FLEA activities during
regularly scheduled work hours must use personal, vacation time, or previously
earned compensation time and must request the time off in advance. The FLEA
President may act on behalf of members to notify management of upcoming
meetings. Management will grant all requests as long as they do not adversely
affect library operations.

== Article IV: TRANSFERS ==

If an employee seeks to transfer from another position within the Library, the
employee's length of service in their previous department will be credited for
determining entitlement to any benefits provided by this Agreement, except that
in posting for any vacancies only length of service in the relevant department
will be considered.

== Article V: MANAGEMENT RIGHTS ==

Subject to the provisions of this Agreement, the following are rights of
Management: the operation of the Departments of the Library covered under this
Agreement, the supervision of its employees and of their work; the making of
reasonable rules to assure orderly and effective work; the making of work
schedules; the determination of what and where duties will be performed and the
establishment of standards of employee competency.

The right to establish and/or revise personnel evaluation programs; the
determination of the method, means and personnel by which the Library's
operations are to be conducted; the determination of the content of the job
classifications, including but not limited to educational and certification
requirements, the appointment, promotion, assignment, direction and transfer of
personnel; the suspension, demotion, discharge or other appropriate disciplinary
action, for just cause, the establishment of reasonable work rules and the
taking of all necessary actions to carry out its mission during emergencies.

Delivery of services to the public will be in the most efficient manner
possible. Such achievement is recognized to be the goal of both parties as they
perform their respective roles and meet their responsibilities.

== Article VI: GRIEVANCE AND ARBITRATION PROCEDURE ==

.Definitions:

[upperalpha]

. For purpose to this Agreement, a grievance is any dispute or difference of
opinion between the Board and an employee covered by this collective bargaining
agreement, or the Association involving the meaning, interpretation or
application of the provisions of this Agreement; provided, however, that in the
event that a grievance is submitted to arbitration under Step 3 of the procedure
set forth herein, the arbitrator shall be limited in the following ways:
[arabic]
.. The Arbitrator shall not amend, modify, nullify, ignore or add to the
provisions of the Agreement.

.. The Arbitrator shall decide only the particular issue(s) presented to the arbitrator
in writing by the parties, and any decision shall be based solely upon a
reasonable interpretation of the meaning or application of the terms of this
Agreement to the facts of the grievance presented.

.. If the matter sought to be arbitrated does not involve an interpretation of
the terms or provisions of this Agreement and the arbitrator shall so rule in
the award, the matter shall not be further entertained by the arbitrator.

.. The rights of management and control of the Library, including but not
limited to the rights to determine the proper operation of the Library, to hire
and promote employees, to set and enforce standards regarding the qualifications
of employees, and to plan, direct and control operations or the services to be
provided by the Library, except as expressly limited by the provisions hereof,
and any applicable laws or regulations, are vested exclusively in the Board and
shall not be subject to arbitration. The purpose of this provision is to make
clear that management rights, not limited by this Agreement, are rights of the
Board, and that arbitration of grievances must be related to matters that are
the subject of this Agreement.

.. Language in this Agreement which excludes any provision, term or part thereof
from arbitration shall be given full force and effect.

. [underline]#Representation of Parties#: Each of the parties to a grievance
shall have the right to consult with and/or be represented by the representative
of their choice.

. [underline]#Time Limits#: All grievances must be filed at the appropriate
beginning step within fifteen (15) days of the date upon which a reasonable
person should have had knowledge of the actual event or occurrence that gave
rise to the grievance. Grievances must specifically state both the nature of the
grievance and the relief sought. Failure of a grievant to file a grievance or an
appeal within specific time limits shall be deemed a withdrawal of the
grievance. Failure of management to issue a decision within the established time
periods will advance the grievance to the next appropriate step of the grievance
procedure.

. [underline]#Withdrawal of Grievance#: A grievance remains the exclusive
property of the grievant at all times. The grievance retains the right to
withdraw a grievance at any time, or at any step of the grievance procedure.
+
Informal Resolution: Nothing within this procedure will be interpreted as a
constraint that limits the right of a grievant to seek a resolution of a
grievance through informal discussion with their immediate supervisor,
provided such resolution is not inconsistent with the terms of this Agreement.
Rather, informal solutions to problems are encouraged by both parties. Recourse
to formal grievance procedure should be a last resort and should follow the
steps described below.

. [underline]#Formal Procedure#

Step I::
The grievant will present the grievance to their immediate supervisor, who
will arrange to have a meeting not more than seven (7) full days after receiving
the grievance. The immediate supervisor will deliver a written decision not more
than ten (10) full days after the grievance meeting.

Step II::
If the grievance is not resolved at Step I, the grievant may appeal the
immediate supervisor's decision by presenting a written copy of the grievance to
the Director of the Library not more than six (6) full days after receiving the
written decision. The grievant shall indicate the reasons for such appeal and
the relief sought. The Director will arrange a meeting not more than seven (7)
full days after receiving the grievance. The Director, or their designee,
will render a decision to the grievant not more than ten (10) full days after
the meeting with a copy to the Association and Board of Library. The decision
will include the reasons on which the decision is based.

Step III::
If the grievance is not resolved at Step II, the grievant shall, within six (6)
full days after receiving the Director's decision, submit the grievance to the
Chairman of the Board of the Personnel Committee of the Library Board of
Directors. The grievant's submission shall set forth the reasons for
dissatisfaction with the decision of the Director, or their designee, and the
requested relief. The Board shall, within a reasonable period of time from the
date of filing of the grievance, meet with the grievant and the Association to
discuss the grievance and, within thirty (30) days of such meeting shall issue
its written decision to the grievant, the Association, and the Director.

Step IV::
If the parties are unable to resolve the grievance to their mutual satisfaction,
such grievance shall be submitted, within ten (10) business days of the issuance
of a decision in Step III, for grievance mediation to the Massachusetts Board of
Conciliation and Arbitration. The parties shall share equally in the grievance
mediation filing cost.

Step V::
If the grievance is not resolved at Step IV, the grievant may request that the
Association submit the grievance to arbitration. Such request must be made in
writing and be submitted within fifteen (15) days of receipt of the Step IV
decision. If the Association deems the grievance meritorious, it may submit a
written Request for Arbitration to the Board and Director within thirty (30)
days of the Step IV decision. Such Request shall be hand delivered or sent via
certified mail.
+
The Association shall make application to the American Arbitration Association
(“AAA”) for the selection of an arbitrator pursuant to the rules of AAA.
+
The arbitrator's decision shall be in writing and will set forth the arbitrator's
findings, conclusions, and reasoning on the issues submitted. The arbitrator
will be without the power or authority to make any decision that requires the
commission of an act prohibited by law or which is in violation of the terms of
this Agreement, nor shall the arbitrator have authority or jurisdiction to add
to, detract from, or in any way alter the provisions of this Agreement. The cost
for the services of the arbitrator will be borne equally by the Board and the
Association.

== Article VII: NON-DISCRIMINATION ==

The Board and Association agree that the provisions of this Agreement shall be
applied to all bargaining unit employees in accordance with the terms and
provisions of state and federal anti-discrimination law. Towards this end the
Board and Association agree that in the application of the terms of this
Agreement, they will not discriminate because of race, color, sex, sexual
orientation, religion, national origin, age, marital status, or handicap.

== Article VIII: SCOPE AND EFFECT ==

[loweralpha]
. It is agreed that any provision of this contract which is held contrary to
law, will not be deemed valid except to the extent permitted by law, but all
other provisions or applications will continue in full force and effect.

. This Agreement incorporates the entire understanding of the parties on all
matters which were subject to negotiations. During the term of this Agreement,
neither party will be required to negotiate with respect to any matter whether
or not covered by this Agreement.

. This Agreement may not be modified in whole or in part by the parties except
by an instrument in writing duly executed by both parties.

== Article IX: SENIORITY ==

Seniority is defined as the employee's length of continuous service with the
Library since their last day of hire in a regular position.

New employees shall be added to the seniority list twelve (12) months after
their date of hire which list shall be prepared every twelve months. This list
shall show the amount of continuous service for each employee.

An employee's continuous service record shall be broken by voluntary
resignation, discharge for just cause, leave of absence exceeding twelve (12)
months and retirement.

Seniority shall be taken into consideration in the scheduling of vacations, days
off and in the calculation of employee benefit accrual.

== Article X: JOB POSTING ==

When a position covered by this Agreement becomes vacant, such vacancy shall be
posted in the Library in the Staff Room, listing the following:

. Date of opening;

. Position title;

. Salary;

. Department, or Departments;

. Hours of work;

. Job description; and

. Closing date for applications.

This notice of vacancy shall remain posted for a period of not less than seven
(7) days. Employees in the bargaining unit who are interested shall apply in
writing to the Director of the Library.

A. Qualified employees will be given fair and equitable consideration for all
permanent jobs that are posted in the Staff Room, as well as any special
projects that may become available.

== Article XI: SUBSTANCE ABUSE POLICY ==

The Board and the Association express their joint determination to deal
cooperatively and constructively with the issue of substance abuse. Alcoholism
and drug dependency is recognized by medical and public health authorities as
one of the prime causes of substandard work performance and impaired family
life. It is important that the Board and the Association recognize the severity
of this issue and that a proper standard of conduct be followed by all employees
of the Library.

Accordingly, it is agreed that Library employees shall not use, possess or
operate under the influence of illegal drugs (including, but not limited to,
marijuana, cocaine or cocaine derivations, LSD, PCP, or restricted narcotics not
lawfully prescribed by a physician) or alcohol while on duty. In addition,
employees with a substance abuse problem are encouraged to use the treatment
services available through their EAP. Such a leave must be requested before the
occurrence or commission of any act subject to disciplinary action.

== Article XII: SICK LEAVE ==

Sick leave shall be granted to eligible employees who are incapacitated for duty
as a result of illness or non work related injury. Appointments for medical or
dental visits may be charged to sick leave; however, the Library and Association
understand and agree that whenever feasible, routine, non-emergency medical
appointments will be scheduled outside of employee's working hours. Sick leave
may not be charged, however, for any period during which the employee was not
scheduled to work (leave of absence, vacation, etc.). Full time employees shall
be credited with sick leave accrued on the basis of 2.31+ hours per work week.
Part-time salaried employees will be credited with sick leave on a pro-rated
basis.

Upon retirement or death of an employee, accumulated sick leave shall be paid in
a lump sum to the employee, or in the case of death, to their spouse or
designated beneficiary. An employee, or their spouse, shall be entitled to
payment for accumulated but unused sick time in accordance with the following
formula, but subject to a total payout cap of fifty-five hundred dollars
($5,500.00): The number of accumulated but unused sick leave hours credited to
an employee at the date of their death or retirement shall be divided by three
and the result shall be multiplied by the effective rate of compensation. The
product of such calculation shall be payable to the employee with their final
paycheck unless such amount exceeds $5,500.00. Such payout is capped at
$5,500.00. The sick leave buy back cap provisions shall not apply to those
employees hired before December 31, 1986.

The Library reserves the right to require a signed doctor's release before
permitting an employee to return to duty after a medical absence. In situations
involving possible abuse of the sick leave policy the Library reserves the right
to require medical proof of illness.

== Article XIII: HEALTH AND WELFARE ==

Employees covered by health insurance shall continue to pay twenty percent (20%)
of the cost of hospital and medical coverage for City-provided HMO coverage. In
addition, should an employee elect to use a non-HMO City plan they may
apply a dollar amount equal to 20% of the HMO premium towards such plan. Both
parties agree to adopt the City of Northampton's health insurance premium
structure. The Board of Trustees of Forbes Library agrees to continue to
authorize payroll deductions for hospital/medical plan premiums, and to continue
Library employees as members of one of the City of Northampton's group plans
provided for health maintenance.

Any employee in an unpaid status while on a leave of absence other than one
attributable to FMLA or Worker's Compensation will be responsible for paying
both the employee and employer portion of their health insurance premium.
Employees who are in an unpaid status on any type of leave exclusive of FMLA or
Worker's Compensation will not accrue benefits during the unpaid portion of the
leave.

== Article XIV: VACATION ==

Those employees on staff as of August 31, 1997 shall have their current vacation
allotment grandfathered for the duration of this Agreement. Employees shall
receive vacation pay as follows:

. Employees having less than five (5) years of service shall receive ten (10)
vacation days.

. Employees having more than five (5) years but less than ten (10) years of
service shall receive fifteen (15) vacation days.

. Employees having more than ten (10) years but less than fifteen (15) years of
service shall receive twenty (20) vacation days.

. Employees having fifteen (15) years or more of service shall receive
twenty-five (25) vacation days.

An employee's terms of service will be based upon the calendar year in which
that employee began at the Forbes. The increase in vacation time due will begin
on the anniversary of the employee's date of hire and be prorated until the
following January 1 when the full amount will be given.

Part-time employees (those employed on a regular scheduled basis at least twenty
(20) hours per week) shall be entitled to vacation leave on a pro rata basis.

Except in cases of bona fide emergency, vacation leave should be requested no
less than two (2) weeks in advance. An employee may not begin the leave year
with a balance in excess of twenty-five (25) vacation days. A member of the
bargaining unit who leaves the employ of Forbes Library shall be paid for
whatever leave balance exists as of the date of termination; no employee may be
paid for more than twenty-five (25) vacation days of leave.

== Article XV: BEREAVEMENT DAYS ==

Bereavement Leave -- In the event of the death of a spouse, child, or domestic
partner as defined as one who stands in place of a spouse and resides with an
employee, paid leave of up to one calendar week (for actual work days missed)
may be granted.

In the event of death of a member of the immediate family of an employee, the
employee may be granted paid leave of up to three work days (for actual work
days missed.) Immediate family is defined as an employee's mother, father,
step-parent, foster parent, step-child, foster child, sister, brother,
grandparent, grandchild, father-in-law, mother-in-law, son-in-law, and
daughter-in-law.

In the case of the death of the employee's following relative, one day of paid
leave may be allowed (for actual work day missed): aunt, uncle, niece, nephew,
brother-in-law, sister-in-law.

With the consent of the Department Head and providing it will not impair/reduce
the effective delivery of services, an employee scheduled to work may be granted
up to four hours of paid leave to attend the service of a deceased co-worker

== Article XVI: REST AND LUNCH PERIODS ==

All employees are entitled to one fifteen minute rest period (a.k.a. “a
break”) per three hours of consecutive work. Breaks must be scheduled with
approval of the supervisor. Breaks may not be taken at the beginning or at the
end of the work day or lunch period except under exceptional circumstances and
only with the approval of a Department Head or the Director.

Employees who work a shift of at least six (6) hours are entitled to a thirty
(30) minute unpaid meal break. Employees are free to leave the workplace during
their thirty (30) minute meal break. Employees must take this unpaid meal break
except under special circumstances and then only with the approval of a
Department Head or the Director.

== Article XVII: HOLIDAYS ==

The following are paid holidays:

. New Years Day
. Martin Luther King Day
. Presidents Day
. Patriots Day
. Memorial Day
. Independence Day
. Labor Day
. Indigenous peoples Day
. Veterans Day
. 1/2 Day Before Thanksgiving
. Thanksgiving Day
. Friday After Thanksgiving
. Last scheduled day before Christmas
. Christmas Day
. Last scheduled day before New Years

Should the Library declare any other day a holiday or skeleton work force day,
the employees not required to work shall receive the day off with pay. Employees
required to work shall be granted time and 1/2 off with pay.

All employees on a full time basis shall receive seven and one half hours (7.5)
pay. All other employees under this agreement shall be paid holiday pay on a
prorated basis, not to exceed seven and one half hours (7.5) of pay.

If a holiday occurs within an employee's vacation time, the employee shall
receive compensatory time equal to the holiday. Part time employees shall
receive compensatory holiday time on a pro rata basis, not to exceed seven and
one half hours (7.5).

An employee on an unpaid leave will not be eligible for holiday pay.

== Article XVIII: JURY PAY ==

An employee who serves on jury duty will continue to receive regular pay from
the library, provided the employee's department head certifies on the payroll
that the employee is absent for jury duty. When payment by the Court for such
jury duty is made, such payment, exclusive of travel or any other allowances,
shall be refunded to the Library by the employee in the following manner: the
employee shall present to their department head either the check from the Court
endorsed over to Forbes Library, or a certification from the Court as the amount
paid together with the employee's personal reimbursement to the Library. The
Library reserves the right to require documentation of jury service before
authorizing payment for such duty.

Employees subpoenaed by the Commonwealth or its subdivisions shall be reimbursed
as if on jury duty.

An employee on jury duty shall be considered as being employed Monday through
Friday.

An employee who is on jury duty for four (4) hours or less in a given day shall
return to work for the remainder of their regular shift, but in no event shall
the time the employee is on jury duty and the time the employee is on their
regular job exceed eight (8) hours in any given day.

== Article XIX: MILITARY LEAVE ==

A military leave of absence without compensation shall be granted to any
employee called to active duty with the United States Armed Forces.

An employee who serves an annual tour of duty with a United States Reserve
component or as a member of the National Guard of the Commonwealth shall receive
the differences between their regular base pay and military pay received for a
period of up to seventeen (17) working days in a calendar year. The Library
need only reimburse the reservist for days corresponding with the employee's
work schedule.

When permitted by law, an employee who is called to active military duty for a
period of more than thirty (30) days may, at the option of the employee,
continue their medical coverage under the same terms and conditions
provided by the contract. This option shall last for one (1) year only and must
be exercised in writing by the employee by the sixtieth (60) day of the
employee's active duty.

== Article XX: FAMILY MEDICAL LEAVE/MATERNITY LEAVE ==

=== A. Maternity:

In case of maternity leave an employee shall be allowed to continue working
until their attending physician determines that they should take maternity
leave. Except as provided below, maternity leave shall be without pay. When
possible the employee shall give the employer two (2) weeks notice prior to
their last day of work. Upon being placed on maternity leave under this article,
the employee may use any sick leave and/or vacation leave credits accrued to
them at their discretion. Maternity leave shall be allowed up to six (6) months
and, with the approval of the supervisor, may be extended for medical reasons.

Such maternity leave shall not affect the employee's right to receive vacation
time, sick leave, bonuses, advancement, seniority, length of service credit,
benefits, plans or programs for which they were eligible at the date of their
leave, and any other advantages or rights of their employment incidental to
their employment position; provided, however, that such maternity leave shall
not be included, when applicable, in the computation of such benefits, rights
and advantages; and provided, further, that the employer need not provide for
the cost of any benefits, plans or programs during their period of maternity
leave unless such employer so provides for all employees on leave of absence.

=== B. FMLA

See Attachment B.

=== C. JOB PROTECTION

When an employee is on leave their job will not be unfairly targeted for
elimination simply because it is temporarily vacant.

== Article XXI: PERSONAL LEAVE AND RELIGIOUS OBSERVANCES ==

All full time employees shall receive four (4) days for personal leave per
calendar year. All other employees (part time) shall receive personal days per
calendar on a pro rata basis.

It is the understanding of both parties that the library will accommodate
requests for time off for religious observances, but that such time must be
taken as personal time. Vacation time can be substituted for this purpose also.

No advance notice is required for Personal Leave. Employees who choose to take
a Personal Day must notify their immediate supervisor as early in the day as
possible that they will be taking a Personal Day. It is expected that employees
will make every effort to notify their supervisor directly or will leave the
message with another staff person. Voice mail or email will no longer be
considered an acceptable way of communicating an absence. Every effort must be
made to speak directly to a staff person.

Unused personal days will be rolled into vacation days before vacation days are
carried over to the next year.

== Article XXII: LONGEVITY COMPENSATION ==

Each full-time employee (i.e. those employees who work regularly at least
thirty-seven and one half (37 1/2) hours per week) shall receive longevity
compensation as follows:

[upperalpha]
. Upon completion of five (5) years of continuous service in paid status of no
less than fifty percent (50%) of an employee's regular scheduled work week, a
sum of one hundred dollars ($100.00) shall be added to the employee's annual
salary and thereafter through the ninth (9th) year of continuous service the
employee shall receive a longevity payment of one hundred dollars ($100.00).

. Upon completion of ten (10) years of continuous service in paid status of no
less than fifty percent (50%) of an employee's regular scheduled work week, a
sum of five hundred dollars ($500.00) shall be added to the employee's annual
salary and thereafter through the fourteenth (14th year) of continuous service
the employee shall receive a longevity payment of five hundred dollars
($500.00).

. Upon completion of fifteen (15) years of continuous service in paid status of
no less than fifty percent (50%) of an employee's regular scheduled work week, a
sum of six hundred dollars ($600.00) shall be added to the employee's annual
salary and thereafter through the nineteenth (19th) year of continuous service
the employee shall receive a longevity payment of six hundred dollars ($600.00).

. Upon completion of twenty (20) years of continuous service in paid status of
no less than fifty percent (50%) of an employee's regular scheduled work week, a
sum of seven hundred dollars ($700.00) shall be added to the employee's annual
salary and thereafter through the twenty-fourth (24th) year of continuous
service the employee shall receive a longevity payment of seven hundred dollars
($700.00).

. Upon completion of twenty-five (25) years of continuous service in paid status
of no less than fifty percent (50%) of an employee's regular scheduled work
week, a sum of eight hundred dollars ($800.00) shall be added to the employee's
annual salary and thereafter through the twenty-ninth (29th) year of continuous
service the employee shall receive a longevity payment of eight hundred dollars
($800.00).

. Upon completion of thirty (30) years, and beginning in FY98 for each
additional year of continuous service in paid status of no less than fifty
percent (50%) of an employee's regular scheduled work week, a sum of nine
hundred dollars ($900.00) shall be added to the employee's annual salary as
their longevity payment.

. Upon completion of thirty-one (31) years of continuous service in paid status
of no less than fifty percent (50%) of an employee's regular scheduled work
week, a sum of nine hundred dollars ($900.00) plus a sum of one hundred dollars
($100.00) shall be added to the employee's annual salary and each year
thereafter the employee shall receive that amount as their longevity payment.

Employees who work at least twenty (20) hours of more per week on a regularly
scheduled basis will have their longevity credited on a pro rata basis, not to
exceed the amount received by full-time employees.

== Article XXIII: ASSOCIATION REPRESENTATION ==

A written list of Officers of the Collective Bargaining Unit shall be furnished
to the Board of Trustees of Forbes Library immediately after their designation
and the Unit shall notify the Board of any changes.

The employees covered by the terms of this Agreement will be allowed to be
represented by the four (4) officers of Collective Bargaining unit.

One (1) member of this committee will be allowed to handle grievances during
working hours. Such time will also be granted in the event that Library
management has requested an investigatory interview during working time with an
employee that may lead to discipline and the employee has requested the presence
of an Association representative. Such meetings will be held at reasonable and
mutually agreed upon times.

The Library agrees to pay for time spent by this committee person during their
regular work hours in consulting with the Board of Trustees of Forbes Library or
its designee regarding grievances.

== Article XXIV: ACCESS TO PREMISES/BULLETIN BOARDS ==

The Library shall permit the Collective Bargaining Unit to post notices on the
bulletin boards in the Staff Room of the Library.

The Library will permit the Unit the use of available Library facilities to
conduct meetings of their organization as long as public use is not disrupted.

== Article XXV: REDUCTION OF STAFF ==

[upperalpha]
. The Board and Association
agree that reductions of the Library staff may be implemented if, in the opinion
of the Board, a decrease in local, state or federal financial support, or other
reason dictates a cutback in the number of employees employed by the Library.

. The Board will notify the Association of such a reduction in a timely fashion.

. The Board agrees that in the event of staff reduction, it shall retain
appropriately qualified staff of the highest quality. The determination of
highest quality will be made by the Director, in consultation with the Board,
after evaluation of program and personnel requirements. The evaluation of
personnel shall be based on seniority and job qualifications. The decision of
the Board in matters of staff reduction shall be final.

. In the event a staff vacancy occurs within twelve (12) months of such a
reduction, laid off staff who are qualified and certified for such a vacancy
will be given preference over other applicants.

== Article XXVI: NO STRIKE, WORK SLOWDOWN OR LOCKOUT ==

The parties agree that during the term of this Agreement differences shall be
resolved by peaceful and appropriate means that do not interrupt or disturb the
Library operation. Accordingly, the Association agrees that during the term of
this Agreement there shall be no strikes, work stoppages, concerted work slow
downs or other concerted refusal to perform normal and customary library duties.
The Board agrees that during the term of this agreement it shall not engage in a
lockout.

== Article XXVII: LEAVE OF ABSENCE ==

Employees shall be eligible for Leaves of Absence after they have completed
their training and orientation (probationary) period.

Unpaid leaves of absence may be granted by the Director with the approval of the
Board of Trustees, in the case where an employee desires leave that is not
covered by the Provisions of the Family Medical Leave Act (“FMLA”).

All requests for unpaid leaves of absence or extension of such leave shall be
submitted in writing to the Director.

== Article XXVIII: DISABILITY ==

The Trustees of Forbes Library agree to develop a light duty policy in
accordance with the Americans With Disabilities Act.

The Library may require an employee, subsequent to injury or disability, to be
examined by its designated physician, at Library expense, prior to being
approved to return to work.

An employee utilizing non-work related sick leave shall be permitted to return
to work within thirty (30) calendar days of the date they stopped working upon
presentation of a note from a treating physician, subject to a request from the
Director of the Library, releasing said employee to return to full duty. The
Board of Trustees of Forbes Library may, at its discretion, provide the employee
with a written job description of their position and require the employee to
present it to their physician.

If an employee is out on sick leave for more than thirty (30) consecutive days
and then seeks to return to duty, the Board of Trustees of Forbes Library may,
at its discretion, require the employee to undergo a medical examination at
Library expense for the purpose of determining the employee's fitness for duty.
The Library shall endeavor to schedule an examination promptly so that the
employee can return to duty if found fit, on the date specified by the treating
physician. In the event that an examination is not scheduled promptly, the
Library will not charge the employee's sick time account for any delay in
returning to work caused by such delay.

If the treating physician and Library-designated physician disagree as to the
employee's fitness to return to duty, the Collective Bargaining Unit and the
Board of Trustees of Forbes Library will jointly select a third independent
physician who shall determine the employee's fitness to return. If the
independent physician agrees that the employee may return to duty, the
employee's sick leave account will not be changed for any delay in returning to
work caused by the invocation of this procedure.

== Article XXIX: MISCELLANEOUS PROVISIONS ==
=== A. Overtime and Flex Time

Employees covered by this Agreement will be paid time and a half for any time
worked above 40 hours in Forbes Library's 7-day work week (Sunday through
Saturday). Any overtime hours must have prior approval by the employee's
supervisor.

Flex Time shall be considered any time worked above an employee's usual salaried
hours but under the 40 hour per week Overtime standard. All staff are encouraged
to balance hours worked in a 2 week pay period to equal the amount of their
salaried hours. With permission of their supervisor, staff would be allowed to
accumulate up to 25 hours of flex time. In unusual circumstances, and with prior
approval of the employee's supervisor and the Library Director, time over 25
hours would be paid out at the employee's usual hourly rate.

=== B. Mileage

The Library agrees to reimburse all employees covered by this Agreement at the
mileage rate used by the City of Northampton.

=== C. Orientation/Probationary Period

New employees shall be covered by the following probationary period:

Non-professional employees (clerical) shall be subject to a 90 day probationary
period.

Professional employees (Librarians) shall be subject to a 180 day
probationary period.

During their probationary period, employees will be eligible for the applicable
provisions of this Agreement except for the Grievance and Arbitration provisions
contained in Article VI. It is understood that if an employee is not judged
suitable for regular status, either upon completion of their probationary
period, or at some point during the probationary period, the Library may
terminate the probationary employee's employment and they shall be without
recourse under the terms of this Agreement.

=== D. Parking

All Forbes Library Employees may park free in the library lot during their
scheduled work shifts. If employees fail to use or display properly the parking
permits that were provided to them, they will be responsible for their own
parking tickets.

=== E. Volunteers

The use of volunteers shall not lead to the replacement, transfer, reassignment,
downgrading, or layoff of bargaining unit employees, to a reduction in their
hours of work, or to the elimination of positions in the bargaining unit.

=== F. Retirement

Management requests that FLEA members give as much notice as possible of retirement.

== Article XXX: COMPENSATION ==

Salary Chart: An accurate salary chart for the time period covered by the
contract will be provided to FLEA as soon as possible, but within at least 60
days of the contract's approval. Each member of FLEA will be given written
notice of their step, grade, and hourly rate when they receive their step raise.
When an employee reaches the final step in a grade, the hourly salary will be
adjusted upward, if needed, to match the highest FLEA member at that grade.

All eligible employees will receive a step raise of 3 1/2 percent per year until
they reach the top of their grade.

Employees who were hired before July 1, 2005 will receive their step raise on
July 1st of every year they are eligible. New employees hired on or after July
1, 2005 will receive their step raises on the anniversary date of their first
day of employment.

All employees are eligible to receive a contractual increase regardless of term of employment.

The Employer agrees to increase an employee's base salaries by two percent
(2.0%) during the period of time beginning July 1, 2019 and ending June 30,
2020.

In the event the Library decides to open on Sundays, then the parties agree to
re-open this Agreement for the purpose of negotiating over the effect of that
decision on bargaining unit employees.

== Article XXXI: LABOR MANAGEMENT COMMITTEE ==

The Library and the Association agree to the formation of a joint labor
management committee to be composed of two Association and two management
employees to discuss matters pertaining to employee relations which may be of
mutual concern to the Association and the Library.

The LMC agrees to meet at least quarterly, or more if mutually agreed upon.
Meetings will be no longer than two hours. Members of the committee will be paid
at their normal rate for their time. Others may be invited to attend a meeting
by mutual consent of committee members, on an unpaid basis.

== Article XXXII: DURATION ==

This Agreement between the Board and the Association entered into this 20th day
of June 2019 covers the period beginning July 1, 2019 and ending on June 30,
2020 provided that the Agreement shall remain in full force and effect until a
successor agreement is negotiated and in effect.
